### ISSUE TITLE
create a 'release'

### ISSUE THREAD

**Issue by craftyguy** [ondrejbudai/libhidx#5]
I was creating a PKGBUILD for hidviz, to add to AUR, but this dependency does not have a release/tagged version I can pull. I don't like the $pkg-git fad, since pulling HEAD is almost always a bad idea for a dependency of an app that has releases/tagged versions.

**Comment by ondrejbudai** [comment]
Hi craftyguy,
please put hidviz with libhidx together in one package for now. Libhidx is currently not ready for public usage because of lacking documentation and often changing API.
If it's problem, I will do my best to solve this problem but I would rather not have this library as seperate package.

I've create #6 to add this info in README.

**Comment by craftyguy** [comment]
@ondrejbudai 
Ah, I see. Your release packages for hidviz does not include libhidx, so hidviz does not build.

**Comment by ondrejbudai** [comment]
That's because it's autogenerated by github and github unfortunately doesn't submodules in it. You can use package at this link: http://hidviz.org/releases/hidviz-0.1.3.tar.gz . It should have the same scheme as the generated one but including libhidx. I will write some info about release packages in README.

**Comment by craftyguy** [comment]
Was that package autogenerated in some way to include the submodule
(libhidx), or did you manually generate that?

**Comment by ondrejbudai** [comment]
In hidviz there's scripts/release.sh script for it.

**Comment by craftyguy** [comment]
Hmm, I cannot use this script in the PKGBUILD since the release file
of hidviz is not a git repo. I'll have to see about some other way to
pull down libhidx

**Comment by ondrejbudai** [comment]
Well, the archive at hidviz.org shoul be enough for building hidviz, isn't it? Sorry, I don't know much about PKGBUILD...

**Comment by craftyguy** [comment]
There is no 'hidviz.org', but the archive tagged in the hidviz github project is not enough to build hidviz, it's missing the libhidx submodule (due to the limitation in github that you pointed out)

**Comment by ondrejbudai** [comment]
There surely is hidviz.org, but currently there's no index except for Hello world. :) But I've uploaded the correct archive containing all dependencies to this domain: http://hidviz.org/releases/hidviz-0.1.3.tar.gz

Is something wrong with building the package from this archive?

**Comment by craftyguy** [comment]
Haha, I saw the 'hello world' and decided that there was no release posted there :)

I'll try that archive right now!

**Comment by ondrejbudai** [comment]
Yeah, it's just placeholder, I've currently have limited time due to school. Sorry about the misunderstanding. :)

**Comment by ondrejbudai** [comment]
0.1.5 released

https://hidviz.org/releases/hidviz-0.1.5.tar.gz

I think this should fix the issue. Feel free to reopen if not.
